<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <brand>
        <headerColor>#0070D2</headerColor>
        <shouldOverrideOrgTheme>false</shouldOverrideOrgTheme>
    </brand>
    <description>Lightning App Used By Training Support Center To Manage Case</description>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <label>TSC Agent Console Lightning</label>
    <navType>Console</navType>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Sales_Opportunity_Record_Page2</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Opportunity</pageOrSobjectType>
        <recordType>Opportunity.Order_Opportunity</recordType>
        <type>Flexipage</type>
        <profile>SB ARC / TSC Agent</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Sales_Opportunity_Record_Page2</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Opportunity</pageOrSobjectType>
        <recordType>Opportunity.Order_Opportunity</recordType>
        <type>Flexipage</type>
        <profile>SB ARC / TSC Manager</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Sales_Opportunity_Record_Page2</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Opportunity</pageOrSobjectType>
        <recordType>Opportunity.Order_Opportunity</recordType>
        <type>Flexipage</type>
        <profile>SB ARC BGST Sales Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Sales_Opportunity_Record_Page2</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Opportunity</pageOrSobjectType>
        <recordType>Opportunity.Order_Opportunity</recordType>
        <type>Flexipage</type>
        <profile>SB ARC BGST Sales User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Sales_Opportunity_Record_Page2</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Opportunity</pageOrSobjectType>
        <recordType>Opportunity.Order_Opportunity</recordType>
        <type>Flexipage</type>
        <profile>SB ARC Business User Profile</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Sales_Opportunity_Record_Page2</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Opportunity</pageOrSobjectType>
        <recordType>Opportunity.Order_Opportunity</recordType>
        <type>Flexipage</type>
        <profile>SB ARC Finance Credit Card  Team</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Sales_Opportunity_Record_Page2</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Opportunity</pageOrSobjectType>
        <recordType>Opportunity.Order_Opportunity</recordType>
        <type>Flexipage</type>
        <profile>SB ARC Invoice Task Force</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Sales_Opportunity_Record_Page2</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Opportunity</pageOrSobjectType>
        <recordType>Opportunity.Order_Opportunity</recordType>
        <type>Flexipage</type>
        <profile>SB ARC Sales BI User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Sales_Opportunity_Record_Page2</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Opportunity</pageOrSobjectType>
        <recordType>Opportunity.Order_Opportunity</recordType>
        <type>Flexipage</type>
        <profile>SB ARC Sales User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Sales_Opportunity_Record_Page2</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Opportunity</pageOrSobjectType>
        <recordType>Opportunity.Order_Opportunity</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>Tab</actionName>
        <content>American_Red_Cross_Service_Console_Home_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>ARC / TSC Agent</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>Tab</actionName>
        <content>ARC_Service_Console_Home_Page_Team_Leads</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>ARC / TSC Manager</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>Tab</actionName>
        <content>ARC_Service_Console_Home_Page_Team_Leads</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <tabs>standard-Account</tabs>
    <tabs>standard-Contact</tabs>
    <tabs>standard-Case</tabs>
    <tabs>standard-LiveChatTranscript</tabs>
    <tabs>standard-LiveAgentSession</tabs>
    <tabs>standard-LightningQuickText</tabs>
    <tabs>redwing__Achievement_Assignment__c</tabs>
    <tabs>ccrz__E_TransactionPayment__c</tabs>
    <uiType>Lightning</uiType>
    <utilityBar>TSC_Agent_Console_Lightning_UtilityBar</utilityBar>
    <workspaceConfig>
        <mappings>
            <tab>ccrz__E_TransactionPayment__c</tab>
        </mappings>
        <mappings>
            <tab>redwing__Achievement_Assignment__c</tab>
        </mappings>
        <mappings>
            <tab>standard-Account</tab>
        </mappings>
        <mappings>
            <tab>standard-Case</tab>
        </mappings>
        <mappings>
            <tab>standard-Contact</tab>
        </mappings>
        <mappings>
            <tab>standard-LightningQuickText</tab>
        </mappings>
        <mappings>
            <tab>standard-LiveAgentSession</tab>
        </mappings>
        <mappings>
            <tab>standard-LiveChatTranscript</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
