public class CancelOrderItemController {
    
    public Static String keyPrefixlrnas;
    public Static String keyPrefixroster;
    
    @AuraEnabled 
    public static List<ccrz__E_OrderItem__c> getOrderItemDetail(String orderId)
    {
    	List<ccrz__E_OrderItem__c> initOrderItem = [SELECT	Id,
		                                             		ccrz__Order__c,
		                                             		ccrz__Price__c,
		                                             		ccrz__Quantity__c,
                                                     		ccrz__ItemTotal__c,
		                                             		ccrz__SubAmount__c,
		                                             		ccrz__Product_Name__c,
		                                             		ccrz__Product__r.ccrz__SKU__c,
		                                             		Inventory_Type__c
		                                               FROM ccrz__E_OrderItem__c
		                                       		  WHERE Id =: orderId LIMIT 1];
        return initOrderItem;
    }
    
    @AuraEnabled 
    public static decimal getCreditedOrderItemDetail(String orderItemId)
    {
        List<AggregateResult> creditedOrderItem = [SELECT   ccrz__ParentOrderItem__c,
                                                   		    SUM(ccrz__ItemTotal__c)
                                                   FROM	    ccrz__E_OrderItem__c
                                                   WHERE    ccrz__ParentOrderItem__c =: orderItemId
                                                   AND 	    Is_Return__c = true
                                                   GROUP BY ccrz__ParentOrderItem__c];
        decimal totalSumAmount;
        
        if(creditedOrderItem.size() > 0)
        {
        	totalSumAmount = decimal.valueOf(creditedOrderItem[0].get('expr0') + '');
            
            system.debug('totalSumAmount***'+totalSumAmount);
        }
        
        return totalSumAmount;
    }
    
    @AuraEnabled 
    public static decimal getCreditedOrderItemCount(String orderItemId)
    {
        List<AggregateResult> previosCreditQty  = [SELECT   ccrz__ParentOrderItem__c,
                                                   			SUM(ccrz__Quantity__c)
                                                   FROM	 	ccrz__E_OrderItem__c
                                                   WHERE    ccrz__ParentOrderItem__c =: orderItemId
                                                   AND 	 	Is_Return__c = true
                                                   GROUP BY ccrz__ParentOrderItem__c];
        decimal totalCrdtQty;
        
        if(previosCreditQty.size() > 0)
        {
        	ccrz__E_OrderItem__c oItem = [SELECT ccrz__Quantity__c  FROM ccrz__E_OrderItem__c WHERE Id =: orderItemId LIMIT 1];
            
            totalCrdtQty = decimal.valueOf(previosCreditQty[0].get('expr0') + '');
            
            system.debug('totalCrdtQty***'+totalCrdtQty);

        }
        
        return totalCrdtQty;
    }
    
    @AuraEnabled 
    public static Map<String, List<String>> getDependentMap(sObject objDetail, string contrfieldApiName,string depfieldApiName)
	{
        String controllingField = contrfieldApiName.toLowerCase();
        String dependentField   = depfieldApiName.toLowerCase();
        
        Map<String,List<String>> objResults = new Map<String,List<String>>();
        
        Schema.sObjectType objType = objDetail.getSObjectType();
        
        if (objType==null)
        {
            return objResults;
        }
        
        Map<String, Schema.SObjectField> objFieldMap = objType.getDescribe().fields.getMap();
        
        if (!objFieldMap.containsKey(controllingField) || !objFieldMap.containsKey(dependentField))
        {
            return objResults;     
        }
        
        Schema.SObjectField theField  = objFieldMap.get(dependentField);
        Schema.SObjectField ctrlField = objFieldMap.get(controllingField);
        
        List<Schema.PicklistEntry> contrEntries = ctrlField.getDescribe().getPicklistValues();
        
        List<PicklistEntryWrapper> depEntries 	= wrapPicklistEntries(theField.getDescribe().getPicklistValues());
        
        List<String> controllingValues = new List<String>();
        
        for (Schema.PicklistEntry ple : contrEntries)
		{
            String label = ple.getLabel();
            
            objResults.put(label, new List<String>());
            
            controllingValues.add(label);
        }
        
        for (PicklistEntryWrapper plew : depEntries)
		{
            String label 		= plew.label;
            String validForBits = base64ToBits(plew.validFor);
            
            for (Integer i = 0; i < validForBits.length(); i++)
            {
                String bit = validForBits.mid(i, 1);
                
                if (bit == '1')
                {
                    objResults.get(controllingValues.get(i)).add(label);
                }
                
            }
        }
        
        return objResults;
        
    }
    
    public static String decimalToBinary(Integer val)
    {
        String bits 	= '';
        
        while (val > 0)
        {
            Integer remainder 	= Math.mod(val, 2);
            val 				= Integer.valueOf(Math.floor(val / 2));
            bits				= String.valueOf(remainder) + bits;
        }
        
        return bits;
    }
    
    public static String base64ToBits(String validFor)
    {
        if (String.isEmpty(validFor)) return '';
        
        String validForBits = '';
        
        for (Integer i = 0; i < validFor.length(); i++)
        {
            String thisChar = validFor.mid(i, 1);
            Integer val = base64Chars.indexOf(thisChar);
            String bits = decimalToBinary(val).leftPad(6, '0');
            validForBits += bits;
        }
        
        return validForBits;
    }
    
    private static final String base64Chars = '' +
        'ABCDEFGHIJKLMNOPQRSTUVWXYZ' +
        'abcdefghijklmnopqrstuvwxyz' +
        '0123456789+/';
    
    
    private static List<PicklistEntryWrapper> wrapPicklistEntries(List<Schema.PicklistEntry> PLEs)
    {
        return (List<PicklistEntryWrapper>)
            JSON.deserialize(JSON.serialize(PLEs), List<PicklistEntryWrapper>.class);
    }
    
    public class PicklistEntryWrapper
    {
        public String activ			{get;set;}
        public String defaultValue  {get;set;}
        public String label			{get;set;}
        public String value			{get;set;}
        public String validFor		{get;set;}
        public PicklistEntryWrapper(){}
    }
    
    
    @AuraEnabled
    public static void cancelOI(String orderId, String orderAdjustmentType, String reasonCodes, String explanation)
    {
        List<ccrz__E_OrderItem__c> oItm = [SELECT Id,
        										  ccrz__OrderItemStatus__c,
                                           		 (SELECT Id
                                                    FROM Training_Event__r),
                                                 (SELECT Id
													FROM Voucher__r),
                                                 (SELECT Id
													FROM Fulfillment_Items__r),
												 (SELECT Id
												    FROM ccrz__Order_Items__r)
                                            FROM ccrz__E_OrderItem__c
                                           WHERE Id =: orderId LIMIT 1];
                                                   
        system.debug('***oItm***'+oItm);
        
        List<Id> tEventIdList  = new List<Id>();
        List<Id> voucherIdList = new List<Id>();
        List<Id> flmtItmIdList = new List<Id>();
        List<Id> oItemIdList   = new List<Id>();
        
        if(oItm.size() > 0)
        {
        	for(ccrz__E_OrderItem__c oi : oItm)
	        {
	        	if( oi.ccrz__OrderItemStatus__c == 'Order Submitted' ||
		        	oi.ccrz__OrderItemStatus__c == 'In Process' 	 ||
		        	oi.ccrz__OrderItemStatus__c == 'Partial Shipped' ||
		        	oi.ccrz__OrderItemStatus__c == 'On Hold' 		 ||
		        	oi.ccrz__OrderItemStatus__c == 'Reservation'	 ||
		        	oi.ccrz__OrderItemStatus__c == 'Shipped')
        		{
		            if(oi.Training_Event__r.size() > 0)
		            {
		                for (Training_Events__c te : oi.Training_Event__r)
		                {
		                	tEventIdList.add(te.Id);
		                }
		            }
		            
		            if(oi.Voucher__r.size() > 0)
		            {
		                for (Voucher__c v : oi.Voucher__r)
		                {
		                	voucherIdList.add(v.Id);
		                }
		            }
		            
		            if(oi.Fulfillment_Items__r.size() > 0)
		            {
		            	for(Fulfillment_Item__c fli : oi.Fulfillment_Items__r)
		            	{
		            		flmtItmIdList.add(fli.Id);
		            	}
		            }
		            
		            if(oi.ccrz__Order_Items__r.size() > 0)
		            {
		            	for(ccrz__E_OrderItem__c fli : oi.ccrz__Order_Items__r)
		            	{
		            		oItemIdList.add(fli.Id);
		            	}
		            }
		            
		            oItemIdList.add(oi.Id);
        		}
	        }
        }
        
        List<Training_Events__c> tsToUpdate			= new List<Training_Events__c>();
        List<Voucher__c> vchrsToUpdate 				= new List<Voucher__c>();
        List<Fulfillment_Item__c> flmtItmsToUpdate 	= new List<Fulfillment_Item__c>();
        List<ccrz__E_OrderItem__c> oItemsToUpdate	= new List<ccrz__E_OrderItem__c>();
        
        if(tEventIdList.size() > 0)
        {
	        for(Id tId : tEventIdList)
	        {
	        	 tsToUpdate.add(new Training_Events__c(Id					= tId,
													   Scheduling_Status__c	= 'Void',
													   Void_Reason__c		= 'Customer Declined'));
	        }
        }
        
        if(voucherIdList.size() > 0)
        {
        	for(Id vId : voucherIdList)
        	{
        		vchrsToUpdate.add(new Voucher__c(Id		   = vId,
        										 Status__c = 'Claimed'));
        	}
        }
        
        if(flmtItmIdList.size() > 0)
        {
        	for(Id flmtId : flmtItmIdList)
        	{
        		flmtItmsToUpdate.add(new Fulfillment_Item__c(Id 		= flmtId,
        													 Status__c 	= 'Cancelled'));
        	}
        }
        
        if(oItemIdList.size() > 0)
        {
        	for(Id oId : oItemIdList)
        	{
        		oItemsToUpdate.add(new ccrz__E_OrderItem__c(Id 				 = oId,
													ccrz__OrderItemStatus__c = 'Cancelled',
													Adjustment_Types__c		 = orderAdjustmentType,
													Reason_Codes__c 		 = reasonCodes,
													Explanation__c			 = explanation));
        	}
        }
        
        if(tsToUpdate.size() > 0)
        {
        	update tsToUpdate;
        }
        
        if(vchrsToUpdate.size() > 0)
        {
        	update vchrsToUpdate; 
        }
        
        if(flmtItmsToUpdate.size() > 0)
        {
        	update flmtItmsToUpdate;
        }
        
        if(oItemsToUpdate.size() > 0)
        {
        	update oItemsToUpdate;
        }
    	
    }
    
    @AuraEnabled
    public static void refundOI(String orderId, String orderAdjustmentType, String reasonCodes, String explanation, decimal qty, String price, Boolean isPartialReturn)
    {
        system.debug('***qty***'+qty);
        system.debug('***price***'+Decimal.ValueOf(price));
        
        ccrz__E_OrderItem__c oItm = [SELECT  Id,
                                             ccrz__Order__c,
                                             ccrz__Price__c,
                                             ccrz__Quantity__c,
                                             ccrz__SubAmount__c,
                                             ccrz__Product_Name__c,
                                             ccrz__ItemTotal__c,
                                             ccrz__PricingType__c,
                                             ccrz__OrderLineType__c,
                                             ccrz__Product__c,
                                             ccrz__ProductType__c,
                                             ccrz__UnitOfMeasure__c,
                                             ccrz__OrderItemStatus__c,
                                             ccrz__StoreId__c,
                                             ccrz__ItemStatus__c,
                                             ccrz__OrderItemId__c,
                                             ccrz__OriginalQuantity__c,
                                             ccrz__OriginalItemPrice__c,
                                             Opportunity__c,
                                             Inventory_Type__c
                                        FROM ccrz__E_OrderItem__c
                                       WHERE Id =: orderId LIMIT 1];
        
        system.debug('***oItm***'+oItm);
        
        if(oItm.ccrz__Order__c != null)
        {
        	ccrz__E_Order__c ccOrder = [SELECT  Id,
        										ccrz__Account__c,
												ccrz__Name__c,
												ccrz__OriginatedCart__c,
												Opportunity_Order__c,
												Error_Message__c,
												ccrz__OrderDate__c,
												ccrz__OrderStatus__c,
												ccrz__CurrencyISOCode__c,
												ccrz__Storefront__c,
												FOCIS_Category__c,
												
												(SELECT Id
												   FROM ccrz__E_Orders__r
                                                  WHERE	Is_Submitted__c  = false),
												(SELECT Id
												   FROM ccrz__TransactionPayments__r)
												   
										   FROM ccrz__E_Order__c
										  WHERE Id =: oItm.ccrz__Order__c];
	        
	        system.debug('**ccOrder**'+ccOrder);
	        
	        boolean hasChildOrder = false;
	        
	        if(ccOrder.ccrz__E_Orders__r.size() > 0)
	        {
	        	hasChildOrder = true;
	        }
	        
	        
		    ccrz__E_Order__c newOrder = ccOrder.clone(false,false,false);
		    
		    if (!hasChildOrder)
		    {
		        newOrder.ccrz__Order__c 		= ccOrder.Id;
		        newOrder.ccrz__OrderStatus__c	= 'Return Submitted';
		        newOrder.Is_Return_Order__c		= true;
		        insert newOrder;
	        }
	        
	        ccrz__E_OrderItem__c newOdrItm = oItm.clone(false,false,false);
	        
	        if (!hasChildOrder)
	        {
	        	newOdrItm.ccrz__Order__c 		= newOrder.Id;
	        }
	        else
	        {
	        	newOdrItm.ccrz__Order__c 		= ccOrder.ccrz__E_Orders__r[0].Id;
	        }
	        newOdrItm.ccrz__Price__c			= decimal.ValueOf(price);
	        newOdrItm.ccrz__Quantity__c 		= qty;
	        newOdrItm.ccrz__SubAmount__c 		= qty * Decimal.ValueOf(price);
	        newOdrItm.ccrz__OrderItemStatus__c 	= 'Return Submitted';
	        newOdrItm.ccrz__ParentOrderItem__c	= oItm.Id;
	        newOdrItm.Is_Return__c				= true;
            /*
            if (isPartialReturn)
	        {
	        	newOdrItm.Is_Partial_Return_OI__c  = true;
	        }
	        else
	        {
	        	newOdrItm.Is_Partial_Return_OI__c  = false;
	        }*/
            
	        insert newOdrItm;
	        
	        system.debug('***newOrdItm***'+newOdrItm);
	        
	        system.debug('***isPartialReturn***'+isPartialReturn);
	        
	        //For DROP STUDENT it should be 
	        if (isPartialReturn)
	        {
	        	oItm.ccrz__OrderItemStatus__c = 'Partial Returned';
                //oItm.Is_Partial_Return_OI__c  = true;
	        }
	        else
	        {
	        	oItm.ccrz__OrderItemStatus__c = 'Returned';
	        }
	        
	        oItm.Adjustment_Types__c	  = orderAdjustmentType;
			oItm.Reason_Codes__c 		  = reasonCodes;
			oItm.Explanation__c			  = explanation;
	        update oItm;
	        
	        ccOrder.ccrz__OrderStatus__c	= 'Returned';
	        update ccOrder;
	        
        }
        
    }
    
    @AuraEnabled
    public static void replaceOI(String orderId, String orderAdjustmentType, String reasonCodes, String explanation, decimal qty){
    	
        
        ccrz__E_OrderItem__c oItm = [SELECT  Id,
                                             ccrz__Order__c,
                                             ccrz__Price__c,
                                             ccrz__Quantity__c,
                                             ccrz__SubAmount__c,
                                             ccrz__Product_Name__c,
                                             ccrz__ItemTotal__c,
                                             ccrz__PricingType__c,
                                             ccrz__OrderLineType__c,
                                             ccrz__Product__c,
                                             ccrz__ProductType__c,
                                             ccrz__UnitOfMeasure__c,
                                             ccrz__OrderItemStatus__c,
                                             ccrz__StoreId__c,
                                             ccrz__ItemStatus__c,
                                             ccrz__OrderItemId__c,
                                             ccrz__OriginalQuantity__c,
                                             ccrz__OriginalItemPrice__c,
                                             Opportunity__c,
                                             Inventory_Type__c
                                        FROM ccrz__E_OrderItem__c
                                       WHERE Id =: orderId LIMIT 1];
        
        system.debug('***oItm-ReplaceOI***'+oItm);
        
        if(oItm != null)
        {
        	ccrz__E_Order__c ccOrder = [SELECT  Id,
        										ccrz__Account__c,
												ccrz__Name__c,
												ccrz__OriginatedCart__c,
												Opportunity_Order__c,
												Error_Message__c,
												ccrz__OrderDate__c,
												ccrz__OrderStatus__c,
												ccrz__CurrencyISOCode__c,
												ccrz__Storefront__c,
												FOCIS_Category__c,
												
												(SELECT Id
												   FROM ccrz__E_Orders__r),
												(SELECT Id
												   FROM ccrz__TransactionPayments__r)
												   
										   FROM ccrz__E_Order__c
										  WHERE Id =: oItm.ccrz__Order__c];
	        
	        system.debug('**ccOrder-ReplaceOI**'+ccOrder);
	        
	        boolean hasChildOrder = false;
	        
	        if(ccOrder.ccrz__E_Orders__r.size() > 0)
	        {
	        	hasChildOrder = true;
	        }
	        
	        
		    ccrz__E_Order__c newOrder = ccOrder.clone(false,false,false);
		    
		    if (!hasChildOrder)
		    {
		        newOrder.ccrz__Order__c 		= ccOrder.Id;
		        newOrder.ccrz__OrderStatus__c	= 'Order Submitted';
		        insert newOrder;
	        }
	        
	        ccrz__E_OrderItem__c newOdrItm = oItm.clone(false,true,false,false);
	        
	        if (!hasChildOrder)
	        {
	        	newOdrItm.ccrz__Order__c 		= newOrder.Id;
	        }
	        else
	        {
	        	newOdrItm.ccrz__Order__c 		= ccOrder.ccrz__E_Orders__r[0].Id;
	        }
	        newOdrItm.ccrz__Price__c			= 0;
	        newOdrItm.ccrz__SubAmount__c 		= 0;
	        newOdrItm.ccrz__OrderItemStatus__c 	= 'Order Submitted';
	        newOdrItm.ccrz__ParentOrderItem__c	= oItm.Id;
	        
	        insert newOdrItm;
	        
	        system.debug('***newOrdItm***'+newOdrItm);
	        
	        oItm.ccrz__OrderItemStatus__c 	= 'Order Submitted';
	        oItm.Adjustment_Types__c	  	= orderAdjustmentType;
			oItm.Reason_Codes__c 		  	= reasonCodes;
			oItm.Explanation__c			  	= explanation;
	        update oItm;
	        
	        ccOrder.ccrz__OrderStatus__c	= 'Order Submitted';
	        update ccOrder;
	        
        }
        
    }
    
    @AuraEnabled
    public static List<voucherWrapper> getVouchers(String orderItemId)
    {
        
        List<voucherWrapper> voucherList = new List<voucherWrapper>();
        
        List<Voucher__c> vouchers = [SELECT Id, 
                                     		Name,
                                     		Voucher_Claim__c,
                                     		User__r.Name   
                                     FROM   Voucher__c
                                     WHERE  CC_Order_Item__c =: orderItemId];
                                     
        if (vouchers.size() > 0)
        {
            for(Voucher__c v : vouchers)
            {
                VoucherWrapper vWrapper = new VoucherWrapper();
                
                vWrapper.voucherId		= v.Id;
                vWrapper.voucherName	= v.Name;
                vWrapper.voucherClaim	= v.Voucher_Claim__c;
                vWrapper.user			= v.User__r.Name;
                
                voucherList.add(vWrapper);
            }
        }
        system.debug('***voucherList***'+voucherList);
        return voucherList;
    }
    
    @AuraEnabled
    public static void dropSlectedStudents(string voucherRecords)
	{
        
        List<Id> 		 voucherListIds 	= new List<Id>();
        List<Voucher__c> vouchersToUpdate 	= new List<Voucher__c>();
        
        if(!string.isBlank(voucherRecords))
        {   
            List<VoucherWrapper> lstVoucherRecords =  (List<VoucherWrapper>) System.JSON.deserialize(voucherRecords,List<VoucherWrapper>.class);
            
            for(VoucherWrapper vRecords : lstVoucherRecords)
            {
                if(vRecords.isSelected)
                {
                    system.debug('***vRecords***'+vRecords);
                    voucherListIds.add(vRecords.voucherId);
                }
            }
        }
        
        system.debug('voucherListIds***'+voucherListIds);
        
        if(voucherListIds.size() > 0)
        {
            for(Id vId : voucherListIds)
            {   
                Voucher__c v = new Voucher__c();
                
                v.Id				= vId;
                v.CC_Order__c		= null;
                v.CC_Order_Item__c	= null;
                v.CC_Cart_Item__c	= null;
                v.Opportunity__c	= null;
                v.RCO_Order_Id__c	= null;
                v.Online_Class__c	= null;
                v.CC_Product__c 	= null;
                v.Account__c		= null;
                v.User__c			= null;
                v.Status__c			= 'Issued';
                
                vouchersToUpdate.add(v);
            }
        }
        
        List<Voucher__c > vouchersWithRosters = [SELECT Id,
														(SELECT Id FROM ILT_Rosters__r)
												 FROM   Voucher__c
												 WHERE 	Id
												 IN 	:voucherListIds];
												 
		List<Id> rosterList = new List<Id>();
		
		for (Voucher__c vwr: vouchersWithRosters)
		{
			if(vwr.ILT_Rosters__r.size() > 0)
			{
				for(redwing__ILT_Roster__c r : vwr.ILT_Rosters__r)
				{
					rosterList.add(r.Id);
				}
			}
		}
		
		system.debug('***rosterList***'+rosterList);
		
		
		if(rosterList.size() > 0)
		{
			system.debug('***rosterList***'+rosterList);
			CancelOrderItemController.cancelEnrollment(rosterList);
		}										 
												 
        
        if (vouchersToUpdate.size() > 0)
        {
            update vouchersToUpdate;
        }
    }
    
    @AuraEnabled
    public static void cancelEnrollment(List<Id> recId) {
    	
    	/*
        //for Roster Object(a36) 
        Schema.DescribeSObjectResult r = redwing__Learning_Assignment__c.sObjectType.getDescribe();
        keyPrefixlrnas = r.getKeyPrefix();
        System.debug('Value of roster id' + keyPrefixlrnas );
        
      //Get the value of learning assignent prefix  
        Schema.DescribeSObjectResult l = redwing__ILT_Roster__c.sObjectType.getDescribe();
        keyPrefixroster = l.getKeyPrefix();
        System.debug('Value of learning assignement id' + keyPrefixroster );*/
        
        //if(recId[0].startsWith(keyPrefixroster)){
        
        List<redwing__ILT_Roster__c> rosterList = [SELECT Id,
        												  redwing__User__c,
        												  redwing__Learning_Assignment__c,
        												  redwing__ILT_Class__c 
                                                   	FROM  redwing__ILT_Roster__c 
                                                   WHERE  Id
													  IN  :recId];
													 	
        system.debug('<><><>rosterList<><><>'+rosterList);
        // Remove learning assignment
        List<redwing__Learning_Assignment__c> assignList = [SELECT 	Id,
        															redwing__User__c,
        															redwing__Training_Plan__c 
                                                            FROM 	redwing__Learning_Assignment__c 
                                                            WHERE 	Id = :rosterList[0].redwing__Learning_Assignment__c];
        
        // Remove learning plan assignments
        List<redwing__Training_Plan_Assignment__c> planAssignList = [SELECT Id,
        																	redwing__User__c 
                                                                     FROM 	redwing__Training_Plan_Assignment__c 
                                                                     WHERE 	redwing__User__c = :rosterList[0].redwing__User__c
																	 AND 	redwing__Training_Plan__c = :assignList[0].redwing__Training_Plan__c];
        
        // Get Learning Plan Achievements
        List<redwing__Training_Plan_Achievement__c> learnPlanAchieveList = [SELECT	Id,
        																			redwing__Training_Plan__c 
                                                                            FROM 	redwing__Training_Plan_Achievement__c 
                                                                            WHERE	redwing__Training_Plan__c = :assignList[0].redwing__Training_Plan__c];
        
        // Remove existing Achievement assignments
        List<redwing__Achievement_Assignment__c> achieveAssignList = [SELECT Id,
        																	 redwing__User__c 
                                                                      FROM	 redwing__Achievement_Assignment__c 
                                                                      WHERE  redwing__User__c = :rosterList[0].redwing__User__c
																	  AND	 redwing__Training_Plan_Achievement__c
																	  IN 	 :learnPlanAchieveList];
        
        
        
        if(rosterList.size()>0)
        {
        	delete rosterList;
        }
        if(rosterList.size()>0)
        {
        	delete assignList;
        }
        if(rosterList.size()>0)
        {
        	delete achieveAssignList;
        }
        if(rosterList.size()>0)
        {
        	delete planAssignList;
        }
        
        // Deleting 'Learning Assignment' record will delete 'ILT Roster' record. 
        //}
        /*
        //for Learning Assignment's record(a3E)
        else if(recId.startsWith(keyPrefixlrnas)){

        // Remove learning assignment
        List<redwing__Learning_Assignment__c> assignList = [Select Id,redwing__User__c,redwing__Training_Plan__c 
                                                            From redwing__Learning_Assignment__c 
                                                            Where Id = :recId and Learning_Record_Type__c = 'Media'];
        
        If(assignList.size()>0){
            // Remove learning plan assignments
            List<redwing__Training_Plan_Assignment__c> planAssignList = [Select Id,redwing__User__c 
                                                                         From redwing__Training_Plan_Assignment__c 
                                                                         Where redwing__User__c = :assignList[0].redwing__User__c AND 
                                                                         redwing__Training_Plan__c = :assignList[0].redwing__Training_Plan__c];
            
            // Get Learning Plan Achievements
            List<redwing__Training_Plan_Achievement__c> learnPlanAchieveList = [Select Id,redwing__Training_Plan__c 
                                                                                From redwing__Training_Plan_Achievement__c 
                                                                                Where redwing__Training_Plan__c = :assignList[0].redwing__Training_Plan__c];
            
            // Remove existing Achievement assignments
            List<redwing__Achievement_Assignment__c> achieveAssignList = [Select Id,redwing__User__c 
                                                                          From redwing__Achievement_Assignment__c 
                                                                          Where redwing__User__c = :assignList[0].redwing__User__c AND 
                                                                          redwing__Training_Plan_Achievement__c IN :learnPlanAchieveList];
            
            delete assignList;        
            delete achieveAssignList;
            delete planAssignList; // deleting plan assignment deletes section assignment too
           }
           
        // Deleting 'Learning Assignment' record will delete 'ILT Roster' record.
            
        }*/       
        

    }
    
    public class VoucherWrapper
	{
        
        @AuraEnabled public boolean isSelected 	{get;set;}
        @AuraEnabled public string voucherId 	{get;set;}
        @AuraEnabled public string voucherName 	{get;set;}
        @AuraEnabled public string voucherClaim {get;set;}
        @AuraEnabled public string user 		{get;set;}

        
        public VoucherWrapper()
        {
            isSelected 		= false;
            voucherName 	= '';
            voucherClaim 	= '';
            user			= '';
        }
    }
}