public class Constants {
    /*This class stores constants used by the OpportunityManagement and OpportunityLineManagement classes*/
	public static final String APPROVAL_LEVEL_MOM = 'MOM';
	public static final String APPROVAL_LEVEL_EXECUTIVE_DIRECTOR = 'Executive Director';
	public static final String APPROVAL_LEVEL_SALES_DIRECTOR = 'Sales Director';
	public static final String APPROVAL_LEVEL_MANAGER = 'Manager';
	public static final String NO_APPROVAL_NEEDED = 'No Approval Needed';
    public static final String APPROVED = 'Approved';
    public static final String BGST_Profile = 'ARC BGST Sales User';
}