global class PHSS_GenerateCSVFileBatch implements Database.Batchable<sOBject>, Database.Stateful {

    //global List<String> csvRowValues;
    //global String csvHeader;
    global List<Fulfillment_Item__c> fulfillmentItemList;
    global List<errorItem> errorItemList; 
    global String regExp;   
    global String documentName;
    global Integer sequenceNumber;
    global Integer recordsProcessed;   
    
    global PHSS_GenerateCSVFileBatch() { 
        //csvRowValues = new List<String>();
        fulfillmentItemList = new List<Fulfillment_Item__c>();
        errorItemList = new List<errorItem>();
        sequenceNumber = 2;
        recordsProcessed = 0;
        // TODO: need to include in regExp soft hyphens and non-breaking space
        regExp = '[¡¢£¤¥¦§¨©ª«¬®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿŒœŠšŸƒ–—‘’‚“”„†‡•…‰€™]';
        String csvHeader = 'Transaction Date,' +
                            'Unit Code,' +
                            'FOCIS Category GL,' +
                            'Bill To Org Name,' +
                            'Bill To Org Address,' + 
                            'Bill To Org City,' +
                            'Bill To Org State,' + 
                            'Bill To Org Zip Code,' + 
                            'Bill To Org Country,' + 
                            'Bill To Org User Field3,' +
                            'Bill To Org Primary Phone,' +
                            'Course Num,' + 
                            'Course Name,' + 
                            'End Date,' +
                            'CRS Comments,' + 
                            'Order Num,' +
                            'Terms,' + 
                            'Transaction Amt,' + 
                            'Bill To Org Id,' + 
                            'Bill To Org Address 2,' +
                            'Bill To Org Bill Contact,' + 
                            'Payment Category GL,' +
                            'Customer PO Num,' + 
                            'Full Name,' + 
                            'CRS/Offering ID,' + 
                            'Per Person Fee,' + 
                            'Number of Students,' + 
                            'Org Type,' +
                            'Nk Payment Id,' + 
                            'Nk Bill to Org Id,' +
                            'Max Instructor Full Name,' + 
                            'AP Code \n';
        // Document name format: ARCINVC_yyyy-mm-dd-hh-mm-ss.csv
        String todayMonth = String.valueOf(Date.today().month());
        String todayDay = String.valueOf(Date.today().day());
        String todayHour = String.valueOf(Datetime.now().hour());
        String todayMin = String.valueOf(Datetime.now().minute());
        String todaySec = String.valueOf(Datetime.now().second());
        if(todayMonth.length()<2) { todayMonth = '0'+ todayMonth; }
        if(todayDay.length()<2) { todayDay = '0'+ todayDay; }
        if(todayHour.length()<2) { todayHour = '0'+ todayHour; }
        if(todayMin.length()<2) { todayMin = '0'+ todayMin; }
        if(todaySec.length()<2) { todaySec = '0'+ todaySec; }        
        documentName = 'ARCINVC_'+String.valueOf(Date.today().year())+'-'+todayMonth+'-'+todayDay+'-'+todayHour+'-'+todayMin+'-'+todaySec+'.csv';
        // Insert Header record
        try {
            insert(new Integration_Files__c(File_Name__c=documentName, Record_Data__c=csvHeader, Sequence_Number__c=1, Target_System__c='CFS'));
        } catch (exception e) {
          
        }        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Name,Transaction_Date__c,' + 
                              'Order_Item__r.Unit_Code__c,' +
                              'Order__r.FOCIS_Category__c,' + 
                              'Order__r.ccrz__Account__r.Name,' +
                              'Order__r.ccrz__Account__r.BillingStreet,' +
                              'Order__r.ccrz__Account__r.BillingCity,' + 
                              'Order__r.ccrz__Account__r.BillingState,' + 
                              'Order__r.ccrz__Account__r.BillingPostalCode,' +
                              'Order__r.ccrz__Account__r.BillingCountry,' + 
                              'Order__r.ccrz__Account__r.Special_Invoicing__c,' + 
                              'Order__r.ccrz__Account__r.Billing_Contact_phone__c,' +
                              'CC_Product__r.ccrz__SKU__c,' +
                              'CC_Product__r.Name,' +
                              'ILT_Class__r.redwing__End_Date__c,' + 
                              'Supplemental_Information__c,' +
                              'Order__r.Name,' + 
                              'Order__r.ccrz__Account__r.Payment_Terms__c,' + 
                              'Fulfillment_Item_Total__c,' +
                              'Order__r.ccrz__Account__r.SABA_LMS_Code__c,' +
                              'Order__r.ccrz__Account__r.Billing_Contact__c,Order__r.ccrz__Account__r.Billing_Contact__r.FirstName,Order__r.ccrz__Account__r.Billing_Contact__r.LastName,' +
                              'Order_Item__r.Payment_Category__c,' +
                              'Order__r.ccrz__PONumber__c,' +
                              // FUTURE - Full Name
                              'Fulfillment__r.Name,' +
                              'Order_Item__r.ccrz__Price__c,' +
                              'Quantity__c,' +
                              // FUTURE/TBD - Org Type 
                              'Id,' +
                              'Order__r.ccrz__Account__r.Saba_Id__c,Order__r.ccrz__Account__r.Id,' +
                              'ILT_Class__c,' +
                              'CC_Product__r.AP_Code__c ' + 
                        'FROM Fulfillment_Item__c WHERE Status__c=\'Ready\' AND Fulfillment__r.Type__c!=\'Receipt\'';
        system.debug('Query: '+query);
        return Database.getQueryLocator(query);
    }
 
    global void execute(Database.BatchableContext BC, List<Fulfillment_Item__c> scope) {
        // QUERY INSTRUCTORS FOR ALL ILT CLASSES
        Set<Id> iltClassIds = new Set<Id>();
        Map<Id,redwing__ILT_Instructor__c> iltCIMap = new Map<Id,redwing__ILT_Instructor__c>();
        for(Fulfillment_Item__c fi: scope) {
            if(fi.ILT_Class__c!=null) {
                iltClassIds.add(fi.ILT_Class__c);
            }
        }
        List<redwing__ILT_Instructor__c > instructors = new List<redwing__ILT_Instructor__c >();
        if(!iltClassIds.isEmpty()) {
            instructors = new List<redwing__ILT_Instructor__c >([SELECT Id,redwing__ILT_Class__c,redwing__Primary__c,redwing__Instructor__r.FirstName,redwing__Instructor__r.LastName 
                                                                 FROM redwing__ILT_Instructor__c 
                                                                 WHERE redwing__ILT_Class__c IN:iltClassIds]);
        }
        for(redwing__ILT_Instructor__c i: instructors) {
            if(iltCIMap.containsKey(i.redwing__ILT_Class__c)) {               
                if(iltCIMap.get(i.redwing__ILT_Class__c).redwing__Primary__c) {
                    iltCIMap.put(i.redwing__ILT_Class__c, i);
                }
            } else {
                iltCIMap.put(i.redwing__ILT_Class__c, i);
            }
        }
        // CREATE ROW FOR EACH FULFILLMENT ITEM
        List<Integration_Files__c> integrationFiles = new List<Integration_Files__c>();
        Boolean isError;
        String errString;
        for(Fulfillment_Item__c fi: scope) {
            isError = false;
            errString = '';
            // Transaction Date - Format 2017/03/21 00:00:00
            Datetime dt = fi.Transaction_Date__c;
            String transactionDate = '';
            if(dt!=null) {
                String day = String.valueOf(dt.day());
                String month = String.valueOf(dt.month());
                if(day.length()<2) { day='0'+day; }
                if(month.length()<2) { month='0'+month; }
                transactionDate = dt.year()+'/'+month+'/'+day+' 00:00:00';
            }
            // Unit Code
            String unitCode = '';
            if(fi.Order_Item__r.Unit_Code__c!=null) {
                unitCode='"' + fi.Order_Item__r.Unit_Code__c + '"';
            }
            // FOCIS Category GL
            String focis = '';
            if(fi.Order__r.FOCIS_Category__c!=null) {
                focis='"' + fi.Order__r.FOCIS_Category__c + '"';
            } else {
                isError = true;
                if(errString!='') {errString=errString+';';}
                errString = errString + 'Order-FOCIS Category';
            }
            // Bill To Org Name - No more than 60 characters, check for special characters
            String accountName = '';
            if(fi.Order__r.ccrz__Account__r.Name!=null) {
                accountName = fi.Order__r.ccrz__Account__r.Name;
                accountName = accountName.replaceAll(regExp, '');
                if(accountName.length()>60) {accountName=accountName.left(60);}
                accountName='"' + accountName + '"';
            }
            // Bill To Org Address - No more than 40 characters, check for special characters
            // Bill To Org Address 2 - No more than 40 characters, check for special characters
            String billingStreet = fi.Order__r.ccrz__Account__r.BillingStreet;
            String street1 = '';
            String street2 = '';           
            if(billingStreet!=null) {
                List<String> stringList = new List<String>();
                stringList = String.valueOf(billingStreet).split('\n');
                system.debug('Billing Street String List: ' + stringList); 
                String street = stringList[0].replaceAll(regExp, '');
                street1 = street;
                if(stringList.size()==1) {
                    if(!String.isEmpty(street) && street.length()>40) {
                        street1 = street.left(40);
                        if(street.length()>80) {
                            street2 = street.substring(40, 80);
                        } else {
                            street2 = street.substring(40);
                        }                        
                    }                   
                } else if(stringList.size()>1) {
                    if(!String.isEmpty(street) && street.length()>41) {
                        street1 = street.left(40);
                    }
                    if(!String.isEmpty(stringList[1])) {
                        street2 = stringList[1].replaceAll(regExp, '');
                        if(street2.length()>40) {
                            street2 = stringList[1].left(40);
                        }
                    }
                } 
                street1 = '"' + street1 + '"';
                if(street2!='') {street2='"'+street2+'"';}                
            } else {
                isError = true;
                if(errString!='') {errString=errString+';';}
                errString = errString + 'Order-Account-Billing Street';
            }
            // Bill To Org City - No more than 30 characters, check for special characters
            String city = '';
            if(fi.Order__r.ccrz__Account__r.BillingCity!=null) {
                city = fi.Order__r.ccrz__Account__r.BillingCity.replaceAll(regExp, '');
                if(city.length()>30) {city=city.left(30);}
                city = '"' + city + '"';
            } else {
                isError = true;
                if(errString!='') {errString=errString+';';}
                errString = errString + 'Order-Account-Billing City';
            }
            // TODO: Update to picklist fields when enabled 
            // Bill To Org State - No more than 2 characters
            String state = '';
            if(fi.Order__r.ccrz__Account__r.BillingState!=null) {
                state = fi.Order__r.ccrz__Account__r.BillingState.replaceAll(regExp, '');
                if(state.length()>2) {
                    isError = true;
                    if(errString!='') {errString=errString+';';}
                    errString = errString + 'Order-Account-Billing State';
                } else {
                    state = '"' + state + '"';
                } 
            } else {
                isError = true;
                if(errString!='') {errString=errString+';';}
                errString = errString + 'Order-Account-Billing State';
            }
            // Bill To Org Zip Code - No more than 10 characters
            String postalCode = '';
            if(fi.Order__r.ccrz__Account__r.BillingPostalCode!=null) {
                postalCode = fi.Order__r.ccrz__Account__r.BillingPostalCode;
                if(postalCode.length()>10) {postalCode=postalCode.left(10);}
                postalCode = '"' + postalCode + '"';
            } else {
                isError = true;
                if(errString!='') {errString=errString+';';}
                errString = errString + 'Order-Account-Billing Postal Code';
            }
            // TODO: Update to picklist fields when enabled 
            // Bill To Org Country - No more than 2 characters
            String country = '';
            if(fi.Order__r.ccrz__Account__r.BillingCountry!=null) {
                country = fi.Order__r.ccrz__Account__r.BillingCountry.replaceAll(regExp, '');
                if(country.length()>2) {
                    isError = true;
                    if(errString!='') {errString=errString+';';}
                    errString = errString + 'Order-Account-Billing Country';
                } else {
                    country = '"' + country + '"';
                }
            }
            // Bill To Org User Field3
            String sInvoicing = '';
            if(!String.isEmpty(fi.Order__r.ccrz__Account__r.Special_Invoicing__c)) {
                sInvoicing = '"' + fi.Order__r.ccrz__Account__r.Special_Invoicing__c + '"';
            }
            // Bill To Org Primary Phone
            String phone = '';
            if(fi.Order__r.ccrz__Account__r.Billing_Contact_phone__c!=null) {
                phone = '"' + fi.Order__r.ccrz__Account__r.Billing_Contact_phone__c + '"';
            }
            // Course Num - No more than 40 characters
            String courseNum = '';
            if(fi.CC_Product__r.ccrz__SKU__c!=null) {
                courseNum = fi.CC_Product__r.ccrz__SKU__c;
                if(courseNum.length()>40) {courseNum=courseNum.left(40);}
                courseNum = '"' + courseNum + '"';
            } else {
                isError = true;
                if(errString!='') {errString=errString+';';}
                errString = errString + 'CC Product-SKU';
            }
            // Course Name, check for special characters
            String courseName = '';
            if(fi.CC_Product__r.Name!=null) {
                courseName = '"' + fi.CC_Product__r.Name.replaceAll(regExp, '') + '"';
            } 
            // End Date - Format 2017/03/21 00:00:00
            Date eDate = fi.ILT_Class__r.redwing__End_Date__c;
            String endDate = '1900/01/01 00:00:00';
            if(eDate!=null) {
                String day = String.valueOf(eDate.day());
                String month = String.valueOf(eDate.month());
                if(day.length()<2) {day='0'+day;}
                if(month.length()<2) {month='0'+month;}
                endDate = dt.year()+'/'+month+'/'+day+' 00:00:00';
            } 
            // CRS Comments - No more than 50 characters, check for special characters
            String crsComments = '';
            if(fi.Supplemental_Information__c!=null) {
                crsComments = fi.Supplemental_Information__c.replaceAll(regExp, '');
                if(crsComments.length()>50) {crsComments=crsComments.left(50);}
                crsComments = '"' + crsComments + '"';
            }
            // Order Num
            String orderNum = '';
            if(fi.Order__r.Name!=null) { 
                orderNum = '"' + fi.Order__r.Name + '"'; 
            }
            // Terms
            String terms = '';
            if(!String.isEmpty(fi.Order__r.ccrz__Account__r.Payment_Terms__c)) {
                terms = '"' + fi.Order__r.ccrz__Account__r.Payment_Terms__c + '"';
            } else {
                isError = true;
                if(errString!='') {errString=errString+';';}
                errString = errString + 'Order-Account-Payment Terms';
            }
            // Transaction Amt  
            Decimal amt = fi.Fulfillment_Item_Total__c;          
            String transactionAmt = String.valueOf(amt);
            if(amt.scale()==1) {transactionAmt=transactionAmt+'0';}
            // Bill To Org Id - No more than 60 characters
            String billToOrgId = '';
            if(fi.Order__r.ccrz__Account__r.SABA_LMS_Code__c!=null) { 
                billToOrgId=fi.Order__r.ccrz__Account__r.SABA_LMS_Code__c;
                if(billToOrgId.length()>60) {billToOrgId=billToOrgId.left(60);}
                billToOrgId = '"' + billToOrgId + '"'; 
            }
            // Bill To Org Bill Contact, check for special characters
            String contactFirstName = fi.Order__r.ccrz__Account__r.Billing_Contact__r.FirstName;
            String contactLastName = fi.Order__r.ccrz__Account__r.Billing_Contact__r.LastName;
            String contactName = '';
            if(fi.Order__r.ccrz__Account__r.Billing_Contact__c!=null) {
                if(contactFirstName!=null && contactLastName!=null) { 
                    contactName = '"' + contactFirstName.replaceAll(regExp, '') + ' ' + contactLastName.replaceAll(regExp, '') + '"'; 
                } else if(contactFirstName==null) {
                    contactName = '"' + contactLastName.replaceAll(regExp, '') + '"';
                }
            } else {
                isError = true;
                if(errString!='') {errString=errString+';';}
                errString = errString + 'Order-Account-Billing Contact';
            }
            // Payment Category GL
            String paymentCategoryGL = '';
            if(fi.Order_Item__r.Payment_Category__c!=null) {
                paymentCategoryGL = '"' + fi.Order_Item__r.Payment_Category__c + '"';
            } else {
                isError = true;
                if(errString!='') {errString=errString+';';}
                errString = errString + 'Order Item-Payment Category';
            }   
            // Customer PO Num, check for special characters
            String po = '';
            if(fi.Order__r.ccrz__PONumber__c!=null) {
                po = '"' + fi.Order__r.ccrz__PONumber__c.replaceAll(regExp, '') + '"';
            }
            // TODO - FUTURE: Full Name
            String fullName = '';            
            // CRS/Offering ID
            String offeringId = '"' + String.valueOf(fi.Fulfillment__r.Name) + '"';       
            // Per Person Fee
            Decimal ppFee = fi.Order_Item__r.ccrz__Price__c;  
            String perPersonFee = '';
            if(ppFee!=null) {
                perPersonFee = String.valueOf(ppFee);
                if(ppFee.scale()==1) {perPersonFee=perPersonFee+'0';}
            } else {
                isError = true;
                if(errString!='') {errString=errString+';';}
                errString = errString + 'Order Item-Price';
            }  
            // Number of Students
            Decimal quantity = fi.Quantity__c;    
            String numStudents = '0';
            if(quantity!=null) {
                numStudents = String.valueOf(quantity.intValue());
            }
            // Org Type
            String orgType = '';           
            // Nk Payment Id
            String paymentId = '"' + fi.Id + '"';
            // Nk Bill to Org Id - If field not populated, then return the Salesforce Account Id
            String sabaId = fi.Order__r.ccrz__Account__r.Saba_Id__c;
            if(sabaId!=null) {
                sabaId = '"' + sabaId + '"';
            } else {
                sabaId = '"' + fi.Order__r.ccrz__Account__r.Id + '"';
            }
            // Max Instructor Full Name
            String instructorName = '';
            if(fi.ILT_Class__c!=null && iltCIMap.containsKey(fi.ILT_Class__c) && iltCIMap.get(fi.ILT_Class__c).redwing__Instructor__c!=null) {
                instructorName = '"';
                if(iltCIMap.get(fi.ILT_Class__c).redwing__Instructor__r.FirstName!=null) {
                    instructorName = instructorName + iltCIMap.get(fi.ILT_Class__c).redwing__Instructor__r.FirstName.replaceAll(regExp, '') + ' ';
                }
                if(iltCIMap.get(fi.ILT_Class__c).redwing__Instructor__r.LastName!=null) {
                    instructorName = instructorName + iltCIMap.get(fi.ILT_Class__c).redwing__Instructor__r.LastName.replaceAll(regExp, '');
                }
                instructorName = instructorName + '"';
            }
            // AP Code
            String apCode = '';
            if(!String.isEmpty(fi.CC_Product__r.AP_Code__c)) {
                apCode='"'+fi.CC_Product__r.AP_Code__c+'"';
            }
            String transactionString =  transactionDate+','+unitCode+','+focis+','+accountName+','+street1+','+
                                        city+','+state+','+postalCode+','+country+','+sInvoicing+','+
                                        phone+','+courseNum+','+courseName+','+endDate+','+crsComments+','+
                                        orderNum+','+terms+','+transactionAmt+','+billToOrgId+','+street2+','+
                                        contactName+','+paymentCategoryGL+','+po+','+fullName+','+offeringId+','+
                                        perPersonFee+','+numStudents+','+orgType+','+paymentId+','+sabaId+','+
                                        instructorName+','+apCode;
            recordsProcessed = recordsProcessed + 1;
            // Add Row
            System.debug('Row: '+transactionString);
            if(isError) { 
                errorItem err = new errorItem();
                err.fiId = fi.Id;
                err.fiName = fi.Name;
                err.fiAmount = fi.Fulfillment_Item_Total__c;
                err.errorDetails = errString;
                errorItemList.add(err);
                //errorItemList.add(new errorItem(fi.Id,fi.Name,fi.Fulfillment_Item_Total__c,errorDetails));
            } else {
                //csvRowValues.add(transactionString);
                integrationFiles.add(new Integration_Files__c(File_Name__c=documentName, Record_Data__c=transactionString, Sequence_Number__c=sequenceNumber, Target_System__c='CFS'));
                fulfillmentItemList.add(fi);
                sequenceNumber++;
            }  
        }
        try {
            for(Fulfillment_Item__c fi: fulfillmentItemList) {
                fi.Status__c='Complete';
            }
            if(!integrationFiles.isEmpty() && !fulfillmentItemList.isEmpty()) {
                insert integrationFiles;
                update fulfillmentItemList;
            }
        } catch (exception e) {
          
        }         
    }
    
    global void finish(Database.BatchableContext BC) {
        System.debug(recordsProcessed + ' records processed.');
/*        AsyncApexJob job = [SELECT Id,Status,NumberOfErrors,JobItemsProcessed,TotalJobItems,CreatedBy.Email
                            FROM AsyncApexJob 
                            WHERE Id = :bc.getJobId()];
        
        // SAVE FILE TO FOLDER   
        // Create CSV file
        ContentVersion cv = new ContentVersion();
        cv.ContentLocation = 'S';
        cv.VersionData = Blob.valueOf(csvHeader + String.join(csvRowValues,'\n'));
        cv.Title = documentName;
        cv.PathOnClient = documentName;
        insert cv; 
        // Get the content document Id from ContentVersion and Folder/Library Ids
        List<ContentDocument> cds = new List<ContentDocument>([SELECT Id FROM ContentDocument WHERE Title=:documentName]);
        List<ContentFolder> folders = new List<ContentFolder>([SELECT Id, Name, ParentContentFolderId FROM ContentFolder WHERE Name = 'CFS Daily Files']);
        List<ContentWorkspace> cws = new List<ContentWorkspace>([SELECT Id, Name FROM ContentWorkspace WHERE Name = 'PHSS Integrations']);
        if(!folders.isEmpty() && !cds.isEmpty() && !cws.isEmpty()) {
            // Create ContentDocumentLink and link to Library
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = cds[0].Id;
            cdl.LinkedEntityId = cws[0].Id; 
            cdl.ShareType = 'I';
            cdl.Visibility = 'AllUsers';
            insert cdl; 
            // Update to place file under the correct integrations folder
            List<ContentFolderMember> cfmList = new List<ContentFolderMember>([SELECT Id, ParentContentFolderId FROM ContentFolderMember WHERE ChildRecordId =:cds[0].Id LIMIT 1]);
            if(!cfmList.isEmpty()) {
                cfmList[0].ParentContentFolderId=folders[0].Id;
                update cfmList[0];
            }            
        }        
*/        
        // TODO: Send an email to the User after your batch completes
        if(!errorItemList.isEmpty()) {
            String csvFileString = 'Fulfillment Item Id,Fulfillment Item Name,Fulfillment Item Total,Error Details \n';
            for(errorItem e: errorItemList) {
                system.debug(e);
                csvFileString = csvFileString + e.fiId + ',' + e.fiName + ',' + e.fiAmount + ',' + e.errorDetails + '\n';
            }
            String body = 'The batch job PHSS_GenerateCSVFileBatch has finished. \n' +
                          'Attached you will find a list of Fulfillment Item Ids that need data verified.';
            String subject = 'Apex Batch Result for PHSS_GenerateCSVFileBatch - Fulfillment Items Not Processed';
            // Create email attachment    
            Messaging.EmailFileAttachment[] emailAttList = new List<Messaging.EmailFileAttachment>();
            Messaging.EmailFileAttachment att = new Messaging.EmailFileAttachment();
            att.setFileName('Fulfillment Items to verify.csv');
            att.setBody(Blob.valueOf(csvFileString));
            emailAttList.add(att);
            // Create email
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setSubject( subject );
            //email.setToAddresses( new String[] {'snehra@salesforce.com'} );
            email.setToAddresses( new String[] {'reportscoa@redcross.org','snehra@salesforce.com'} );
            email.setPlainTextBody( body );
            email.setFileAttachments(emailAttList);
            Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
        }  
    }
    global class errorItem {
        public Id fiId {get; set;}
        public String fiName {get; set;}
        public Decimal fiAmount {get; set;}
        public String errorDetails {get; set;}
        public errorItem() {}
    }
}